### ISSUE TITLE
Will this project be maintained ?

### ISSUE THREAD

**Issue by perrze** [alan-turing-institute/apricot#45]
HI,
I intend to use this project for authentication in my non-profit but I was wondering if you planned to maintained this project ?

Indeed, if not, I will probably fork it.
Thanks for your answer !

**Comment by jemrobinson** [comment]
Hi @perrze. We are planning to maintain this at the moment. If there's any change to this in the future then we'll let the community know. The project is always open to PRs in either case.

Thanks!
